server:
  port: 8081

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            -id: device-service
            url: http://device-service:8082
            predicates:
                - Path=/api/devices/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/smart-city