server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        -id: device-service
        url: https://localhost:8080
        predicates:
          -Path=/api/devices/**