server:
  port: 8083

spring:
  application:
    name: monitoring-service

  datasource:
    url: jdbc:postgresql://postgres-monitoring:5432/${MONITORING_DB_NAME}
    username: ${MONITORING_DB_USER}
    password: ${MONITORING_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/smart-city
          jwk-set-uri: http://keycloak:8080/realms/smart-city/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: monitoring-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.fitgeek.shared.events"
        spring.json.type.mapping: >-
          deviceCreated:com.fitgeek.shared.events.DeviceCreatedEvent,
          sensorReading:com.fitgeek.shared.events.SensorReadingEvent

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG