server:
  port: 8081

spring:
  application:
    name: monitoring-service

  datasource:
    url: jdbc:postgresql://localhost:5432/monitoring_db
    username: postgres
    password: 1331

  kafka:

    bootstrap-servers: kafka:9092

    consumer:

      group-id: monitoring-group

      auto-offset-reset: earliest