server:
  port: 8083

spring:
  application:
    name: monitoring-service

  datasource:
    url: jdbc:postgresql://postgres-device:5432/device_db
    username: device
    password: device

  kafka:

    bootstrap-servers: kafka:9092

    consumer:

      group-id: monitoring-group

      auto-offset-reset: earliest
