server:
  port: 8082

spring:
  application:
    name: device-service

  datasource:
    url: jdbc:postgresql://postgres-device:5432/${DEVICE_DB_NAME}
    username: ${DEVICE_DB_USER}
    password: ${DEVICE_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/smart-city
          jwk-set-uri: http://keycloak:8080/realms/smart-city/protocol/openid-connect/certs


  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG