spring:
  application:
    name: device-service

  datasource:
    url: jdbc:postgresql://postgres-device:5432/device_db
    username: device
    password: device

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/smart-city

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

  flyway:
    enabled: true